spring:
 cloud:
   gateway:
     globalcors:
       cors-configurations:
         '[/**]':
           allowedOrigins: "https://docs.spring.io"
           allowedMethods:
             - GET
             - POST
             - PUT
             - DELETE
     routes:
       - id: restaurant-service
         uri: http://localhost:8086
         predicates:
           - Path=/restaurant/**
         filters:
           - AuthenticationFilter

       - id: employee-service
         uri: http://localhost:8089
         predicates:
           - Path=/api/employee/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: http://localhost:9898
         predicates:
           - Path=/auth/**

 application:
   name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

