spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5436/bi_system?currentSchema=inventory
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083
