spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: restaurant-service
  datasource:
    url: jdbc:postgresql://localhost:5436/bi_system
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
feign:
  auth-service: http://localhost:9898/auth
  employee-service: http://localhost:8089/api/employee