spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: restaurant-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: ${SERVER_PORT}
